web/router.ex
defmodule SportScore.Router do
  use SportScore.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Openmaize.Authenticate
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug Openmaize.Authenticate
  end

  scope "/", SportScore do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index, as: :home
    post "/confirm", PageController, :confirm
    #get "/askreset", PageController, :askreset
    post "/askreset", PageController, :askreset_password
    #get "/reset", PageController, :reset
    post "/reset", PageController, :reset_password
    #get "/login", PageController, :login, as: :login
    post "/login", PageController, :login_user, as: :login
    get "/twofa", PageController, :twofa
    post "/twofa", PageController, :login_twofa
    delete "/logout", PageController, :logout, as: :logout
    post "/register", PageController, :register
  end

  scope "/api", SportScore do
    pipe_through :api
    resources "/sports", SportController, except: [:new, :edit]
    post "/sports/search", SportController, :search
  end

  # Other scopes may use custom stacks.
  # scope "/api", SportScore do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule SportScore.LayoutView do
  use SportScore.Web, :view

  def user_name(%{email: email}) do
    email |> String.split("@") |> hd |> String.capitalize
  end
  def user_name(%{username: username}) do
    username |> String.capitalize
  end
  def user_name(_), do: "The Black Knight"
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Hello SportScore!</title>
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

</head>

<body id="sportscore">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
        data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a v-link="{ path: '/' }" class="navbar-brand">SportScore</a>
    </div>

    <% current_user =  nil %>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li v-link="{ path: '/upcoming' }" class="btn">
          <a>Upcoming Events</a>
        </li>
        <%= if current_user  do %>
        <li v-link="{ path: '/myevents'}" class="btn">
          <a >My Events</a>
        </li>
        <% end %>
        <li v-link="{ path: '/sports'}" class="btn">
          <a >Sports</a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= if @current_user do %>
        <li><a href="<%= #user_path(@conn, :show, @current_user[:id]) %>"><%= user_name @current_user %></a></li>
        <li><%= link "Logout", to: logout_path(@conn, :logout), method: :delete %></li>
        <%= else %>
        <li >
          <a v-link="{ path: '/login'}">Login</a> /
          <a v-link="{ path: '/register' }">Register</a>
        </li>
      <%= end %>
      </ul>
    </div>
  </div>
</nav>
<div class="container-fluid">
  <p class="alert alert-info alert-dismissible" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger alert-dismissible" role="alert"><%= get_flash(@conn, :error) %></p>

  <main role="main">
    <router-view keep-alive></router-view>
  </main>
</div > <!-- /container --><!-- /container -->


<script>window.userToken = "<%= get_csrf_token %>"</script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<!-- JavaScript -->
<script src="//cdn.jsdelivr.net/alertifyjs/1.7.1/alertify.min.js"></script>

<!-- CSS -->
<link rel="stylesheet" href="//cdn.jsdelivr.net/alertifyjs/1.7.1/css/alertify.min.css"/>
<!-- Default theme -->
<link rel="stylesheet" href="//cdn.jsdelivr.net/alertifyjs/1.7.1/css/themes/default.min.css"/>
<!-- Semantic UI theme -->
<link rel="stylesheet" href="//cdn.jsdelivr.net/alertifyjs/1.7.1/css/themes/semantic.min.css"/>
<!-- Bootstrap theme -->
<link rel="stylesheet" href="//cdn.jsdelivr.net/alertifyjs/1.7.1/css/themes/bootstrap.min.css"/>
<script src="<%= static_path(@conn, "/js/app.js") %>"></script>
</body>
</html>